#!/bin/bash

set -eu

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Source YunoHost helpers
. /usr/share/yunohost/helpers
. _common

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

# Retrieve app settings
app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get "$app" domain)


dockerapp_ynh_loadvariables

#=================================================
# MODIFY A CONFIG FILE
#=================================================

dockerapp_ynh_findreplaceallvaribles

#=================================================
# STOP AND REMOVE SERVICE
#=================================================

# docker rm
dockerapp_ynh_rm

#=================================================
# START AND CREATE SERVICE
#=================================================

# docker run
dockerapp_ynh_run

#=================================================
# NGINX CONFIGURATION
#=================================================

# Modify Nginx configuration file and copy it to Nginx conf directory
dockerapp_ynh_preparenginx

#=================================================
# SETUP SSOWAT
#=================================================



#=================================================
# RELOAD NGINX
#=================================================

# Reload Nginx and regenerate SSOwat conf
dockerapp_ynh_reloadservices
